Finalize?

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -2,5 +2,9 @@
 # bin/detect <build_path>
 set -e
 
-echo "Detect OK"
-exit 0
+if [[ -f "traefik.yml" ]]; then
+  exit 0
+else
+  echo "Cannot find traefik.yml!"
+  exit 1
+fi
